############################
## Author
############################

author:
  name: "4stroblog"
  image: author.jpeg
  greeting: "Bienvenidos a mi blog personal"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/4strodev
 

###############################
## OpenGraph & Twitter Cards
###############################

title: "4stroblog"
description: "A geek's personal blog. Here you can read about software development and tech"
images:
  - thumbnail.jpeg
